batch_size: 12
binary_target: Cardiomegaly
data_paths:
- /PATH/TO/CheXpert-v1.0-small
dataset_name: chexpert_pm
device: cuda
eval_every_n_epochs: 10
img_size: 224
loss: cross_entropy
lr: 0.0005
milestones: 150,250
model_name: vit_b_16_torchvision
model_savedir: /PATH/TO/checkpoints
num_epochs: 300
optimizer: sgd
pretrained: true
store_every_n_epochs: 500
wandb_api_key: YOUR_WANDB_KEY
wandb_project_name: chexpert-training
