artifacts_file: data/artifacts_isic.json
batch_size: 12
cav_mode: cavs_max
checkpoint_dir_corrected: /PATH/TO/checkpoints_corrected
ckpt_path: PATH
data_paths:
- /PATH/TO/ISIC2019
dataset_name: isic
device: cuda
dir_precomputed_data: /PATH/TO/precomputed_data
img_size: 224
layer_name: features.29
method: AClarc
model_name: vgg16
wandb_api_key: YOUR_WANDB_KEY
wandb_project_name: isic-data-annotation
