artifact: artificial
artifact_type: ch_time
attacked_classes: &id001
- 1
batch_size: 12
cav_mode: cavs_max
cav_scope: *id001
checkpoint_dir_corrected: /PATH/TO/checkpoints_corrected
ckpt_path: PATH
criterion: all_logits_random
data_paths:
- /PATH/TO/hyper-kvasir
dataset_name: hyper_kvasir_attacked
device: cuda
dir_precomputed_data: /PATH/TO/precomputed_data
direction_mode: signal
img_size: 224
lamb: 5000000.0
layer_name: features.27
loss: cross_entropy
lr: 0.005
method: RRClarc
model_name: vgg16
num_epochs: 2
optimizer: sgd
p_artifact: 0.1
plot_alignment: false
time_format: datetime
wandb_api_key: YOUR_WANDB_KEY
wandb_project_name: r2r-hyper-kvasir-attacked-mitigation
