artifact: artificial
artifact_type: microscope
attacked_classes:
- MEL
batch_size: 12
cav_mode: cavs_max
checkpoint_dir_corrected: /PATH/TO/checkpoints_corrected
ckpt_path: PATH
data_paths:
- /PATH/TO/ISIC2019
dataset_name: isic_attacked
device: cuda
dir_precomputed_data: /PATH/TO/precomputed_data
img_size: 224
layer_name: features.6
method: AClarc
model_name: vgg16
p_artifact: 0.2
wandb_api_key: YOUR_WANDB_KEY
wandb_project_name: isic-attacked-microscope-data-annotation
