artifact_type: ch_time
attacked_classes:
- 1
batch_size: 12
checkpoint_dir_corrected: /PATH/TO/checkpoints_corrected
ckpt_path: PATH
data_paths:
- /PATH/TO/hyper-kvasir
dataset_name: hyper_kvasir_attacked
device: cuda
dir_precomputed_data: /PATH/TO/precomputed_data
img_size: 224
layer_name: features.6
method: AClarc
model_name: vgg16
p_artifact: 0.1
time_format: datetime
wandb_api_key: YOUR_WANDB_KEY
wandb_project_name: kvasir-attacked-data-annotation
