artifact_type: defective_lead
attacked_classes:
- 4
batch_size: 12
data_paths:
- /PATH/TO/PTB-XL/data
dataset_name: ptb_xl_attacked
device: cuda
eval_every_n_epochs: 5
img_size: 224
lead_ids:
- 1
loss: binary_cross_entropy
lr: 0.001
milestones: 50,75
model_name: xresnet1d50
model_savedir: /PATH/TO/checkpoints
num_epochs: 100
optimizer: adam
p_artifact: 0.5
pretrained: false
seq_length: 100
store_every_n_epochs: 500
wandb_api_key: YOUR_WANDB_KEY
wandb_project_name: ptb-attacked-training
