artifact_type: defective_lead
attacked_classes:
- 1
batch_size: 12
cav_mode: cavs_max
checkpoint_dir_corrected: /PATH/TO/checkpoints_corrected
ckpt_path: PATH
data_paths:
- /PATH/TO/PTB-XL/data
dataset_name: ptb_xl_attacked
device: cuda
dir_precomputed_data: /PATH/TO/precomputed_data
img_size: 224
layer_name: features.4.3
lead_ids:
- 1
method: AClarc
model_name: xresnet1d50
p_artifact: 0.5
seq_length: 100
wandb_api_key: YOUR_WANDB_KEY
wandb_project_name: ptb-xl-attacked-data-annotation
