artifact: artificial
artifact_type: defective_lead
attacked_classes:
- 1
batch_size: 12
checkpoint_dir_corrected: /PATH/TO/checkpoints_corrected
ckpt_path: PATH
data_paths:
- /PATH/TO/PTB-XL/data
dataset_name: ptb_xl_attacked
device: cuda
dir_precomputed_data: /PATH/TO/precomputed_data
img_size: 224
lamb: 10.0
layer_name: features.7.3
lead_ids:
- 1
loss: binary_cross_entropy
lr: 0.001
method: RRR_ExpMax
model_name: xresnet1d50
num_epochs: 10
optimizer: adam
p_artifact: 0.5
plot_alignment: false
seq_length: 100
wandb_api_key: YOUR_WANDB_KEY
wandb_project_name: r2r-ptb-xl-attacked-mitigation
