artifact_type: ch_time
attacked_classes:
- 1
batch_size: 128
data_paths:
- /mnt/dataset_hyper_kvasir
dataset_name: hyper_kvasir_attacked
device: cuda
eval_every_n_epochs: 30
img_size: 224
loss: cross_entropy
lr: 0.005
milestones: 150,250
model_name: vit_b_16_torchvision
model_savedir: /mnt/output
num_epochs: 300
optimizer: adam
p_artifact: 0.1
pretrained: true
store_every_n_epochs: 500
time_format: datetime
wandb_api_key: YOUR_WANDB_KEY
wandb_project_name: hyper-kvasir-attacked-training
