alpha: 0.2
artifact: artificial
artifact_type: white_color
attacked_classes:
- 1
batch_size: 12
binary_target: Cardiomegaly
cav_mode: cavs_max
cav_scope:
- 1
checkpoint_dir_corrected: /PATH/TO/checkpoints_corrected
ckpt_path: /media/pahde/Data/r2r-extended/models/chexpert_attacked_v3/resnet50d_adam_lr0.005_p_artifact0.1_alpha0.2_binaryTarget-Cardiomegaly_pm_last.pth
criterion: all_logits_random
data_paths:
- /PATH/TO/CheXpert-v1.0-small
dataset_name: chexpert_pm_attacked
device: cuda
dir_precomputed_data: /PATH/TO/precomputed_data
direction_mode: signal
img_size: 224
lamb: 1
layer_name: identity_1
loss: cross_entropy
lr: 0.005
method: PClarc
model_name: resnet50d
num_epochs: 0
optimizer: adam
p_artifact: 0.1
plot_alignment: false
wandb_api_key: YOUR_WANDB_KEY
wandb_project_name: r2r-chexpert-attacked-mitigation
