batch_size: 12
cav_mode: cavs_max
checkpoint_dir_corrected: /PATH/TO/checkpoints_corrected
ckpt_path: PATH
data_paths:
- /PATH/TO/PTB-XL/data
dataset_name: ptb_xl
device: cuda
dir_precomputed_data: /PATH/TO/precomputed_data
img_size: 224
layer_name: features.7.3
method: AClarc
model_name: xresnet1d50
wandb_api_key: YOUR_WANDB_KEY
wandb_project_name: TEST-ptb-xl-data-annotation
