batch_size: 12
binary_target: Cardiomegaly
checkpoint_dir_corrected: /PATH/TO/checkpoints_corrected
ckpt_path: PATH
data_paths:
- /PATH/TO/CheXpert-v1.0-small
dataset_name: chexpert_pm
device: cuda
dir_precomputed_data: /PATH/TO/precomputed_data
img_size: 224
layer_name: features.3
method: AClarc
model_name: vgg16
wandb_api_key: YOUR_WANDB_KEY
wandb_project_name: chexpert-pm-data-annotation
