artifacts_file: data/artifacts_hyperkvasir.json
batch_size: 12
checkpoint_dir_corrected: /PATH/TO/checkpoints_corrected
ckpt_path: PATH
data_paths:
- /PATH/TO/hyper-kvasir
dataset_name: hyper_kvasir
device: cuda
dir_precomputed_data: /PATH/TO/precomputed_data
img_size: 224
layer_name: features.3
method: AClarc
model_name: vgg16
wandb_api_key: YOUR_WANDB_KEY
wandb_project_name: kvasir-data-annotation
