artifact: artificial
artifact_type: microscope
attacked_classes:
- MEL
batch_size: 12
cav_mode: cavs_max
cav_scope:
- 0
checkpoint_dir_corrected: /PATH/TO/checkpoints_corrected
ckpt_path: /media/pahde/Data/r2r-extended/models/isic_attacked_microscope_v1/resnet50d_p_artifact0.2_p_backdoor0_adam_lr0.001_last.pth
criterion: all_logits_random
data_paths:
- /PATH/TO/ISIC2019
dataset_name: isic_attacked
device: cuda
dir_precomputed_data: /PATH/TO/precomputed_data
direction_mode: signal
img_size: 224
lamb: 1
layer_name: last_conv
loss: cross_entropy
lr: 0.001
method: ReactivePClarc
model_name: resnet50d
num_epochs: 0
optimizer: adam
p_artifact: 0.2
plot_alignment: false
wandb_api_key: YOUR_WANDB_KEY
wandb_project_name: r2r-isic-attacked-mitigation
